//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonagensAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personagens
    {
        public int ID { get; set; }
        public string FotoUrl { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public string NomeReal { get; set; }
        public string Genero { get; set; }
        public string Altura { get; set; }
        public string Peso { get; set; }
        public string Poderes { get; set; }
        public string Habilidades { get; set; }
        public string Afiliacoes { get; set; }
        public string Origem { get; set; }
    }
}
